### PR TITLE
[feat] Split explorable separator ("/") into its own element

### PR DESCRIPTION
**Pull request by liamcain**
## Goal

Before this change, the folder name and `/` character were in the same `<span>`, meaning the separator could not be styled on its own.

There's no functional issue, this was just a minor visual frustration of mine that I attempted to fix. 

#### Default theme
image

#### Minimal theme
image

## Explanation of the changes

To facility this change, the `.explorable` element is no longer rendered using redom `list()`; the list function was not flexible enough to allow having the explorables and the separators as top level components. I didn't want to wrap the `/` element inside the explorable span since I thought it made more sense if the separator was not included in the highlight when the menu is open:
image

### Alternatives I considered

The other route I considered was removing the `/` from the HTML entirely and creating the separator with an `:after` pseudo-selector in CSS. I opted not to do this since I wanted to leverage Obsidian's `setIcon` function to render the chevron instead of drawing the shape in CSS. Happy to reopen this route though if you'd prefer a smaller footprint.

### Other callouts

I was originally going to include changing the separator to a chevron but since this is easily doable with CSS, I opted to exclude this from the pull request. If you like the change, I can add it back.

#### Example

image

### CODE REVIEW

**Comment by pjeby** [comment]
So, first off, highlighting the separator along with the folder name was actually an intentional choice, to echo Windows Explorer's dropdowns (which highlight both the folder name and the separator).

Second, rather than do away with the list, I would prefer to instead wrap the inner contents in their own spans if that's needed for styling.  You can always forcibly style the / or other separator to not be highlighted if you wish, though the QE default should remain.

I'd be willing to look at a change that doesn't do away with the list or change anything in the default rendering, and preferably doesn't change any of the included CSS, which required a lot of tricky tradeoffs and experimentation to make work with a variety of themes.  If CSS changes are absolutely required, I'll need to know what and why, as well as what the impact is on existing themes both with and without explicit support for QE.

**Comment by liamcain** [comment]
Sounds good, I updated the changes to be a lot lighter weight. Now I just wrap the text and the separator in their own spans. 

The styling I'm after is still achievable with the following snippet now:

---

```css
.explorable-separator {
  content: "/";
  color: var(--text-muted);
  box-sizing: border-box;
  position: relative;
  width: 12px;
  height: 12px;
  border: 1px solid transparent;
  border-radius: 100px;
}

.explorable-separator::after {
  content: "";
  display: block;
  box-sizing: border-box;
  position: absolute;
  width: 5px;
  height: 5px;
  border-bottom: 1px solid;
  border-right: 1px solid;
  transform: rotate(-45deg);
  right: 3px;
  top: 5px;
}
```

**Comment by pjeby** [comment]
Getting better!  But there's no need to change the CSS or thrash the DOM if you do something like this:

```typescript
nameEl: HTMLSpanElement = <span class="explorable-path"/>;
sepEl: HTMLSpanElement = <span class="explorable-separator">&nbsp;/&nbsp;</span>
el: HTMLSpanElement = <span draggable class="explorable titlebar-button">{this.nameEl}{this.sepEl}</span>;
```

And then set the text of `this.nameEl` and do `this.sepEl.toggle(index < items.length-1)`, instead of destroying and recreating DOM elements in the update method.  (Re:DOM is not a virtual dom/diffing system; it's a set of helpers for doing direct DOM modification, much the same way Obsidian core does things.)

(Also if you can flatten this to a single commit, that would be nice.)

**Comment by liamcain** [comment]
Great suggestion! Just updated it with your changes and rebased to get everything in one commit.

**Comment by pjeby** [comment]
Er, it looks like you kept the CSS changes?  The idea of putting the text back in the separator was so that the existing CSS wouldn't change *at all*, only the HTML structure.

**Comment by liamcain** [comment]
My thinking with the CSS change was that it makes it a lot easier for customizing the separator character. Users could just include a snippet like:

```css
.explorable-separator {
  content: "›";
}
```

However, after playing around with CSS, I was able to mimic the styling without the need for modifying the CSS. So I removed the CSS changes and added the `/` back to the markup.


<details>
    <summary>Including my CSS snippet just for completeness</summary>

```css
.explorable {
  display: inline-block;
  height: 20px;
}

.explorable:not(:last-child):after {
  content: "›";
  color: var(--text-muted);
  margin: 0 8px;
}

.explorable-path {
  border-radius: 2px;
  font-size: 10px;
  height: 20px;
  padding: 2px 6px;
}

.explorable-separator {
  display: none;
}

#quick-explorer .explorable.selected,
#quick-explorer .explorable:hover {
  background-color: transparent !important;
}

#quick-explorer .explorable.selected .explorable-path,
#quick-explorer .explorable:hover .explorable-path {
  background-color: var(--interactive-accent);
}

```
</details>

**Comment by pjeby** [comment]
Ah.  Then wouldn't it be possible to just reduce the CSS change in QE to be putting the " / " (non-breaking spaces) as the default content for `#quick-explorer .explorable-separator`?  I'd be okay with that, as long as it doesn't introduce any sizes, margins, positions, etc. -- i.e., no "magic numbers".

I mean, if you're tired of this and don't want to mess with it any more, I'm okay with that too; I can take it from here if you like.

**Comment by liamcain** [comment]
> Then wouldn't it be possible to just reduce the CSS change in QE to be putting the " / " (non-breaking spaces) as the default content for #quick-explorer .explorable-separator?

That's what the previous commit was (https://github.com/pjeby/quick-explorer/commit/710bfef). There's just some margin in substitute of the `nsbp;`s.

**Comment by pjeby** [comment]
Right - as I said way back, I don't want CSS changes that might interact differently with different themes.  Keeping the text the same shouldn't affect existing themes. But I'm also fine with keeping the change as it currently is, just noting that if you'd rather do the text replacement in CSS that's fine since it should still be the same measurements.

So, I can either accept this as is, or move the separator text into CSS to make replacement easier.  Do you have a preference?

**Comment by liamcain** [comment]
I think having the separator defined in CSS is better since it's more intuitive for users trying to apply custom styling.

**Comment by pjeby** [comment]
Ok.  Would you like me to do it, or you?

**Comment by pjeby** [comment]
I've gone ahead and implemented this in 0.1.12, with the separator in CSS.  Thanks for your patience.

**Comment by liamcain** [comment]
Sorry, didn't have a chance to follow-up. Thanks for adding this! 

Also, now I see what you meant by only including the `content`, you replaced the margin I had added with the non-breaking spaces. Makes sense!

**Comment by pjeby** [comment]
Yeah, I hate fiddling with magic numbers in CSS with Obsidian; I'd much rather use font-based measurements or no numbers at all if I can avoid it, so that it's not immediately wrong in every theme that isn't specifically written to work around it.

**Pull request closed without merging**
